"""
LifecycleStateMachine — pure business logic that operates on the Session
passed in by the caller. Stateless: no module-level DB session, safe to
share across requests.
"""
from datetime import datetime, timedelta
from typing import Dict, List, Optional
from uuid import UUID

from sqlalchemy.orm import Session

from models import Notification, User, UserActivity


# Notifications generated by milestone reminders embed the trigger name in
# their `notification_type` so dedup can filter exactly without parsing the
# human-readable message text.
MILESTONE_NOTIFICATION_PREFIX = "milestone_reminder"


def _milestone_notification_type(trigger_name: str) -> str:
    return f"{MILESTONE_NOTIFICATION_PREFIX}:{trigger_name}"


class LifecycleStateMachine:
    """Manages user lifecycle progression through exam preparation stages."""

    STAGES = [
        "class_10_completed",
        "class_11_started",
        "class_12_started",
        "class_12_completed",
        "entrance_exams_preparing",
        "undergraduate_started",
        "competitive_exams_preparing",
        "post_graduation",
        "career_started",
    ]

    CAREER_PATHS = {
        "engineering": ["jee_main", "jee_advanced", "bitsat", "viteee"],
        "medical": ["neet", "aiims", "jipmer"],
        "commerce": ["cat", "mat", "xat"],
        "science": ["iisc", "tifr", "ncbs"],
        "civil_services": ["upsc_prelims", "upsc_mains"],
        "defense": ["nda", "cds", "afcat"],
    }

    @staticmethod
    def _parse_iso(value: Optional[str]) -> Optional[datetime]:
        if not value:
            return None
        try:
            return datetime.fromisoformat(value)
        except (TypeError, ValueError):
            return None

    def check_stage_progression(self, db: Session, user_id: UUID) -> Optional[str]:
        user = db.query(User).filter(User.id == user_id).first()
        if not user:
            return None

        current_stage = user.current_stage
        now = datetime.utcnow()
        triggers: Dict = user.milestone_triggers or {}

        if current_stage == "class_12_started":
            d = self._parse_iso(triggers.get("board_exam_date"))
            if d and d < now:
                return "class_12_completed"

        if current_stage == "entrance_exams_preparing":
            for key in ("jee_result_date", "neet_result_date"):
                d = self._parse_iso(triggers.get(key))
                if d and d < now:
                    return "college_admission_phase"

        if current_stage == "college_admission_phase":
            d = self._parse_iso(triggers.get("college_start_date"))
            if d and d < now:
                return "undergraduate_started"

        return None

    def progress_user_stage(self, db: Session, user_id: UUID, new_stage: str) -> bool:
        """Atomically advance a user's stage and record the transition."""
        user = db.query(User).filter(User.id == user_id).first()
        if not user:
            return False

        # Capture from_stage BEFORE mutation so the activity log is accurate.
        from_stage = user.current_stage
        if from_stage == new_stage:
            return False

        user.current_stage = new_stage
        user.updated_at = datetime.utcnow()

        self._generate_milestone_triggers(user, new_stage)

        db.add(Notification(
            user_id=user_id,
            notification_type="stage_progression",
            message=(
                f"Congratulations! You've progressed to "
                f"{new_stage.replace('_', ' ').title()} stage."
            ),
            scheduled_at=datetime.utcnow(),
            channel="push",
        ))

        db.add(UserActivity(
            user_id=user_id,
            activity_type="stage_progression",
            details={"from_stage": from_stage, "to_stage": new_stage},
            timestamp=datetime.utcnow(),
        ))

        db.commit()
        return True

    def _generate_milestone_triggers(self, user: User, new_stage: str) -> None:
        triggers: Dict = {}
        now = datetime.utcnow()

        if new_stage == "class_12_completed":
            triggers.update({
                "jee_application_start": (now + timedelta(days=30)).isoformat(),
                "neet_application_start": (now + timedelta(days=60)).isoformat(),
                "jee_exam_date": (now + timedelta(days=120)).isoformat(),
                "neet_exam_date": (now + timedelta(days=150)).isoformat(),
            })
        elif new_stage == "college_admission_phase":
            triggers.update({
                "college_start_date": (now + timedelta(days=90)).isoformat(),
                "semester_exam_date": (now + timedelta(days=120)).isoformat(),
            })
        elif new_stage == "undergraduate_started":
            career_paths = user.career_paths or []
            if isinstance(career_paths, list) and "engineering" in career_paths:
                triggers.update({
                    "gate_preparation_start": (now + timedelta(days=365 * 2)).isoformat(),
                    "internship_season": (now + timedelta(days=365 * 2 + 180)).isoformat(),
                })

        # Column is JSON — assign the dict directly.
        user.milestone_triggers = triggers

    def recommend_next_exams(self, db: Session, user_id: UUID) -> List[Dict]:
        """Return exam recommendations for a user. Pure read."""
        user = db.query(User).filter(User.id == user_id).first()
        if not user:
            return []

        career_paths = user.career_paths or []
        if not isinstance(career_paths, list):
            career_paths = []
        current_stage = user.current_stage
        recommendations: List[Dict] = []

        if current_stage in ("class_12_started", "class_12_completed"):
            if "engineering" in career_paths:
                recommendations.extend([
                    {"exam": "jee_main", "priority": "high", "reason": "Primary engineering entrance exam"},
                    {"exam": "bitsat", "priority": "medium", "reason": "Alternative private engineering option"},
                    {"exam": "viteee", "priority": "medium", "reason": "VIT engineering entrance"},
                ])
            if "medical" in career_paths:
                recommendations.append(
                    {"exam": "neet", "priority": "high", "reason": "Medical entrance exam"},
                )
        elif current_stage == "undergraduate_started":
            if "engineering" in career_paths:
                recommendations.extend([
                    {"exam": "gate", "priority": "high", "reason": "Postgraduate engineering studies"},
                    {"exam": "cat", "priority": "medium", "reason": "MBA preparation"},
                ])

        return recommendations

    def run_daily_checks(self, db: Session) -> None:
        """Batch lifecycle check (cron-style). Caller owns the session."""
        for user in db.query(User).all():
            new_stage = self.check_stage_progression(db, user.id)
            if new_stage:
                self.progress_user_stage(db, user.id, new_stage)
            self._check_milestone_triggers(db, user)

    def _check_milestone_triggers(self, db: Session, user: User) -> None:
        triggers: Dict = user.milestone_triggers or {}
        if not isinstance(triggers, dict):
            return
        now = datetime.utcnow()
        emitted = False

        for trigger_name, trigger_date_str in triggers.items():
            trigger_date = self._parse_iso(trigger_date_str)
            if not trigger_date:
                continue

            notification_date = trigger_date - timedelta(days=7)
            if now < notification_date:
                continue

            notif_type = _milestone_notification_type(trigger_name)
            # Exact-match dedup — far more reliable than the old
            # message.contains(trigger_name) check, which never matched
            # because the user-facing text doesn't include the trigger name.
            existing = db.query(Notification).filter(
                Notification.user_id == user.id,
                Notification.notification_type == notif_type,
            ).first()
            if existing:
                continue

            db.add(Notification(
                user_id=user.id,
                notification_type=notif_type,
                message=self._generate_milestone_message(trigger_name, trigger_date),
                scheduled_at=now,
                channel="push",
            ))
            emitted = True

        if emitted:
            db.commit()

    def _generate_milestone_message(self, trigger_name: str, trigger_date: datetime) -> str:
        messages = {
            "jee_application_start": f"JEE Main applications open in 7 days ({trigger_date.strftime('%B %d')}). Start preparing your documents!",
            "neet_application_start": f"NEET applications open in 7 days ({trigger_date.strftime('%B %d')}). Ensure you have all required certificates!",
            "jee_exam_date": f"JEE Main exam in 7 days ({trigger_date.strftime('%B %d')}). Final revision phase begins now!",
            "neet_exam_date": f"NEET exam in 7 days ({trigger_date.strftime('%B %d')}). Focus on high-weightage topics!",
            "college_start_date": f"College starts in 7 days ({trigger_date.strftime('%B %d')}). Get ready for your academic journey!",
            "gate_preparation_start": "Time to start GATE preparation! Exam is in 2 years.",
            "internship_season": "Internship season approaching. Start building your resume and projects!",
        }
        return messages.get(trigger_name, f"Milestone approaching: {trigger_name.replace('_', ' ').title()}")


# Stateless singleton — holds no DB session, safe to share.
lifecycle_machine = LifecycleStateMachine()
